## install.packages('remotes')
## install.packages('tidyverse') # collection of R packages for data manipulation, analysis, and visualisation
## install.packages('lubridate') # working with dates and times
## remotes::install_github('eco4cast/neon4cast') # package from NEON4cast challenge organisers to assist with forecast building and submission

# ------ Load packages -----
library(tidyverse)
library(lubridate)
#--------------------------#

# Change this for your model ID
# Include the word "example" in my_model_id for a test submission
# Don't include the word "example" in my_model_id for a forecast that you have registered (see neon4cast.org for the registration form)
my_model_id <- 'example_ID'

# --Model description--- #

# Model utilizes air temperature as a primary driver of water temperature for the next day. 

# -- Uncertainty representation -- #

# Driver, process, and parameter uncertainty are all accounted for. Parameter uncertainty was addressed by having the model draw a value from a parameter distribution generated from a linear regression model. Driver uncertainty is accounted for by using 31 ensemble members from the NOAA forecast of air temperature at each site. Process uncertainty was generated by drawing from a normal distribution of the residuals from an initial linear model.

#------- Read data --------
# read in the targets data
targets <- read_csv("https://sdsc.osn.xsede.org/bio230014-bucket01/challenges/targets/project_id=neon4cast/duration=P1D/aquatics-targets.csv.gz")

# read in the sites data
aquatic_sites <- read_csv("https://raw.githubusercontent.com/eco4cast/neon4cast-ci/refs/heads/main/neon4cast_field_site_metadata.csv") |>
  dplyr::filter(aquatics == 1)

focal_sites <- aquatic_sites |> 
  filter(field_site_subtype == 'Lake') |> 
  pull(field_site_id)

# Filter the targets
targets <- targets %>%
  filter(site_id %in% focal_sites,
         variable == 'temperature')

#--------------------------#


# ------ Weather data ------
met_variables <- c("air_temperature","surface_radiation")

# Past stacked weather -----
weather_past_s3 <- neon4cast::noaa_stage3()

weather_past <- weather_past_s3  |> 
  dplyr::filter(site_id %in% focal_sites,
                datetime >= ymd('2017-01-01'),
                variable %in% met_variables) |> 
  dplyr::collect()

# aggregate the past to mean values
weather_past_daily <- weather_past |> 
  mutate(datetime = as_date(datetime)) |> 
  group_by(datetime, site_id, variable, parameter) |> 
  summarize(prediction = mean(prediction, na.rm = TRUE), .groups = "drop") |> 
  # convert air temperature to Celsius if it is included in the weather data
  mutate(prediction = ifelse(variable == "air_temperature", prediction - 273.15, prediction)) |> 
  pivot_wider(names_from = variable, values_from = prediction)


past_three <- weather_past_daily |> 
  group_by(site_id) |> 
  mutate(atemp_lag1 = lag(air_temperature, n=1),
         atemp_lag2 = lag(air_temperature, n=2),
         atemp_lag3 = lag(air_temperature, n=3),
         atemp_three_mean = (atemp_lag1 + atemp_lag2 + atemp_lag3)/3)

# Future weather forecast --------
# New forecast only available at 5am UTC the next day
forecast_date <- Sys.Date() 
noaa_date <- forecast_date - days(1)

weather_future_s3 <- neon4cast::noaa_stage2(start_date = as.character(noaa_date))

weather_future <- weather_future_s3 |> 
  dplyr::filter(datetime >= forecast_date,
                site_id %in% focal_sites,
                variable %in% met_variables) |> 
  collect()

weather_future_daily <- weather_future |> 
  mutate(datetime = as_date(datetime)) |> 
  # mean daily forecasts at each site per ensemble
  group_by(datetime, site_id, parameter, variable) |> 
  summarize(prediction = mean(prediction, na.rm = TRUE), .groups = "drop") |> 
  # convert air temperature to Celsius if it is included in the weather data
  mutate(prediction = ifelse(variable == "air_temperature", prediction - 273.15, prediction)) |> 
  pivot_wider(names_from = variable, values_from = prediction) |> 
  select(any_of(c('datetime', 'site_id', met_variables, 'parameter')))

# Generate average values for past three days across dataframe
## Initialize arrays that will store loop values

#l_date <- c()
#l_site <- c()
#l_avg <- numeric()

#for(i in 1:length(focal_sites)){
 # curr_site <- focal_sites[i]
 # curr_site_weather <- weather_past_daily |> filter(site_id == curr_site)
 # print(curr_site)
  #for(j in 1:length(curr_site_weather$datetime)){
   # curr_date <- curr_site_weather$datetime[j]
    #if(j<9){
     # l_avg<-append(l_avg,NA)
      #l_date<-append(l_date,curr_date)
      #l_site<-append(l_site,curr_site)
    #}else{
     # pthree_weather <- curr_site_weather |> 
      #  filter(datetime %in% ((seq.Date(as.Date(curr_date-days(8)),as.Date(curr_date-1),by="day")))) |> 
       # subset(datetime!=curr_date-4)
      #Debugging stuff below
      #print(length(pthree_weather$air_temperature))
      #for(val in 1:length(pthree_weather)){
        #print(paste(curr_date, pthree_weather$air_temperature[val]))
      #}
      #print("-----------")
      #avg <- mean(pthree_weather$air_temperature, na.rm = TRUE)
      #print(paste("D:",curr_date,"AVG", avg))
    #  l_avg<-append(l_avg,avg)
     # l_date<-append(l_date,curr_date)
      #l_site<-append(l_site,curr_site)
      #pthree_weather <- pthree_weather[0,]
    #}
  #}
#}

#pthree_avg_df <- do.call(rbind, Map(data.frame, datetime=l_date, site_id=l_site, average_air=l_avg))
#--------------------------#

forecast_horizon <- 30
forecasted_dates <- seq(from = ymd(forecast_date), to = ymd(forecast_date) + forecast_horizon, by = "day")
n_members <- 310

# ----- Fit model & generate forecast----

# Generate a dataframe to fit the model to 
targets_lm <- targets |> 
  pivot_wider(names_from = 'variable', values_from = 'observation') |> 
  left_join(past_three, by = c("site_id", "datetime"))
  

forecast_df <- NULL

# Loop through each site to fit the model
set.seed(123)
for(i in 1:length(focal_sites)) {  
  
  #curr_site <- focal_sites[i]
  curr_site<-focal_sites[i]
  
  site_target <- targets_lm |>
    filter(site_id == curr_site) 
  
  noaa_future_site <- weather_future_daily |> 
    filter(site_id == curr_site)
  
  weather_ensemble_names <- unique(noaa_future_site$parameter)
  
  site_target <- site_target |> 
    mutate(lag1 = lag(temperature,n=2)) |> 
    na.omit()
  
  filtered_historical_weather <- weather_past_daily |> 
    filter(datetime < min(forecasted_dates),
           site_id == curr_site) 
  
  combined_weather <- bind_rows(filtered_historical_weather, noaa_future_site) |> 
    group_by(parameter) |> 
    mutate(atemp_lag1 = lag(air_temperature, n=1),
           atemp_lag2 = lag(air_temperature, n=2),
           atemp_lag3 = lag(air_temperature, n=3),
           three_mean = (atemp_lag1 + atemp_lag2 + atemp_lag3)/3)
  
  #Fit linear model based on past data: water temperature = m * air temperature + b
  #you will need to change the variable on the left side of the ~ if you are forecasting oxygen or chla
  fit <- lm(site_target$temperature ~ site_target$air_temperature + site_target$atemp_three_mean + site_target$lag1)
  fit_summary <- summary(fit)
  mod <- predict(fit, data = model_data)
  mod <- c(NA, mod)
  
  #Identify coefficients, standard error, and residuals
  coeffs <- round(fit$coefficients, 2)
  params_se <- fit_summary$coefficients[,2]
  residuals <- fit$residuals

  # fit <- lm(site_target$temperature ~ ....)
  # Parameter uncertainty prereqs
  param_df <- data.frame(beta1 = rnorm(n_members, coeffs[1], params_se[1]),
                         beta2 = rnorm(n_members, coeffs[2], params_se[2]),
                         beta3 = rnorm(n_members, coeffs[3], params_se[3]),
                         beta4 = rnorm(n_members, coeffs[4], params_se[4]))
              # beta1 corresponds to intercept, beta2 corresponds to slope of air temperature, beta3 corresponds to past weekly average air temperature
  
  #Process uncertainty prereqs
  sigma <- sd(residuals, na.rm = TRUE)
  

  #need a distribution of initial conditions rnorm
  if(site_target$datetime[nrow(site_target)] == forecast_date){
    initD <- data.frame(temperature = rnorm(n_members, mean = targets_lm$lag1[nrow(targets_lm)], sd = params_se[4]), ensemble = seq(1:n_members))
  }else{
    rSamp <- sample(site_target$temperature, 30)
    initD <- data.frame(temperature = rnorm(n_members, mean = mean(rSamp), sd = sd(rSamp)), ensemble = seq(1:n_members))
  }
  # Loop through all forecast dates
  
  for (t in 1:length(forecasted_dates)) {
    print(forecasted_dates[t])
    
    # use linear regression to forecast water temperature for each ensemble member
    # You will need to modify this line of code if you add additional weather variables or change the form of the model
    # The model here needs to match the model used in the lm function above (or what model you used in the fit)
    
    # Loop over each ensemble member

    
    met_ens_id <- 0

    for(ens in 1:n_members){
      #allows for indexing of ensemble members past 31 (max number input NOAA ensemble members)
      print(c(focal_sites[i],t,ens))
      if(met_ens_id <= 30){
        met_ens_id <- met_ens_id + 1
        ens_nm <- paste0(ens, "-", met_ens_id)
      }else{
        met_ens_id <- 1
      }
      
      met_ens <- weather_ensemble_names[met_ens_id]
      
      if(t==1){
        init <- initD |> filter(ensemble == ens)
      }else{
        init<- forecast_df |> filter(site_id == curr_site, datetime==forecasted_dates[t-1]) |> filter(parameter==ens)
        print(nrow(init))
      }
      
      #pull driver ensemble for the relevant date; here we are using all 31 NOAA ensemble members
      temp_driv <- weather_future_daily %>%
        filter(datetime == forecasted_dates[t],
               site_id == curr_site,
               parameter == met_ens)
      
      avg_air <- combined_weather |> 
        filter(datetime == forecasted_dates[t],
               site_id == curr_site,
               parameter == met_ens)
      
      # avg_driv <- pthree_avg_df %>%
      #filter(datetime == forecast_date,
      #site_id == curr_site)
      
      
      forecasted_temperature <- param_df$beta1[ens] + param_df$beta2[ens] * temp_driv$air_temperature + param_df$beta3[ens]*avg_air$three_mean + param_df$beta4[ens]*init$temperature + rnorm(n=1, mean=0, sd=sigma)
      
      # put all the relevant information into a tibble that we can bind together
      curr_site_df <- tibble(datetime = as.Date(forecasted_dates[t]),
                             reference_datetime = forecast_date,
                             site_id = curr_site,
                             parameter = ens,
                             temperature = forecasted_temperature,
                             variable = "temperature") #Change this if you are forecasting a different variable
      
      forecast_df <- dplyr::bind_rows(forecast_df, curr_site_df)
    
    }
  }
  message(curr_site, ' forecast run')
}
forecast_df <- rename(forecast_df, prediction = temperature)

#---- Covert to EFI standard ----

# Make forecast fit the EFI standards
forecast_df_EFI <- forecast_df %>%
  filter(datetime > forecast_date) %>%
  mutate(model_id = my_model_id,
         family = 'ensemble',
         duration = 'P1D',
         parameter = as.character(parameter),
         project_id = 'neon4cast') %>%
  select(datetime, reference_datetime, duration, site_id, family, parameter, variable, prediction, model_id, project_id)
#---------------------------#



# ----- Submit forecast -----
# Write the forecast to file
theme <- 'aquatics'
date <- forecast_df_EFI$reference_datetime[1]
forecast_name <- paste0(forecast_df_EFI$model_id[1], ".csv")
forecast_file <- paste(theme, date, forecast_name, sep = '-')

write_csv(forecast_df_EFI, forecast_file)

neon4cast::forecast_output_validator(forecast_file)


neon4cast::submit(forecast_file =  forecast_file, ask = FALSE) # if ask = T (default), it will produce a pop-up box asking if you want to submit

#--------------------------#

forecast_df_EFI |> 
  ggplot(aes(x=datetime, y=prediction, group = parameter)) +
  geom_line() +
  facet_wrap(~site_id) +
  labs(title = paste0('Forecast generated for ', forecast_df_EFI$variable[1], ' on ', forecast_df_EFI$reference_datetime[1]))

plot_file_name <- paste0("Submit_forecast/", forecast_df_EFI$variable[1], '-', forecast_df_EFI$reference_datetime[1], ".png")
ggsave(plot_file_name)


